name: Hook Docs

on:
  push:
    branches:
      - main

jobs:
  hookdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm install, and build docs
        run: |
          npm install
          npm run build:docs
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        env:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./hookdocs
