name: Sync assets with wordpress.org

on:
  push:
    paths:
      - 'readme.txt'
      - '.wordpress-org/**'

jobs:
  run:
    runs-on: ubuntu-latest
    name: Push assets to wporg
    steps:
        - uses: actions/checkout@v4
        - name: WordPress.org plugin asset/readme update
          uses: 10up/action-wordpress-plugin-asset-update@stable
          env:
            SLUG: woocommerce-pos
            IGNORE_OTHER_FILES: true
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
