name: Sync assets with wordpress.org

on:
  release:
    types: [ published ]
    paths:
      - 'readme.txt'
      - '.wordpress-org/**'
jobs:
  run:
    runs-on: ubuntu-latest
    name: Push assets to wporg
    steps:
        - uses: actions/checkout@v2.3.5
        - name: WordPress.org plugin asset/readme update
          uses: selul/action-wordpress-plugin-asset-update@develop
          env:
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}