name: Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          tools: composer, cs2pr, phpcs

      - name: Build
        run: |
          yarn install
          composer install

      - name: Linting the code
        run: npm run lint
        continue-on-error: true

      - name: Running the tests
        run: npm run test
