name: Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          yarn install
          composer install --no-dev

      - name: Linting the code
        run: yarn lint
        continue-on-error: true

      - name: Running the tests
        run: yarn test
