name: Tests
on:
  push:
    branches:
      - main
    paths:
      - "**.php"
      - "**.tsx"
      - "**.ts"

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: composer, cs2pr, phpcs

      - name: Build
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: |
          yarn install
          composer prefix-dependencies
          composer install

      - name: Start WordPress Environment
        run: npm run wp-env start --xdebug=coverage
  
      - name: Check WooCommerce Activation
        run: npm run wp-env run cli -- wp plugin list

      - name: Linting the code
        run: |
          vendor/bin/phpcs -i
          vendor/bin/phpcs --config-show
          # vendor/bin/phpcs --report=checkstyle | cs2pr
          npm run lint
        continue-on-error: true

      - name: Running the tests
        run: | 
          npm run test
          # cat phpunit.xml | cs2pr
