name: Deploy to WP Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          yarn install
          composer install --no-dev
          yarn settings build

      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: wcposdev
          # Deploy Options
          SRC_PATH: "./"
          REMOTE_PATH: "wp-content/plugins/woocommerce-pos"
          FLAGS: -azvr --inplace --delete --exclude-from=$GITHUB_WORKSPACE/.distignore
          #          SCRIPT: "path/yourscript.sh"
          CACHE_CLEAR: TRUE
